openapi: 3.0.3
info:
  title: Department - Employee API
  description: API for managing departments and their employees.
  version: 1.0.0
servers:
  - url: https://api.ejemplo.com

paths:
  /departments:
    get:
      summary: Get all departments
      responses:
        "200":
          description: List of all departments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Department"
    post:
      summary: Create a new department
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DepartmentInput"
      responses:
        "201":
          description: Department created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Department"

  /departments/{id}:
    get:
      summary: Get a department by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Department found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Department"
        "404":
          description: Department not found
    put:
      summary: Update a department by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DepartmentInput"
      responses:
        "200":
          description: Department updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Department"
    delete:
      summary: Delete a department by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Department deleted

  /employees:
    get:
      summary: Get all employees
      responses:
        "200":
          description: List of all employees
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
    post:
      summary: Create a new employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeInput"
      responses:
        "201":
          description: Employee created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"

  /employees/{id}:
    get:
      summary: Get an employee by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Employee found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "404":
          description: Employee not found
    put:
      summary: Update an employee by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeInput"
      responses:
        "200":
          description: Employee updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
    delete:
      summary: Delete an employee by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Employee deleted

  /departments/{id}/employees:
    get:
      summary: Get all employees by department ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: List of employees in the department
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
        "404":
          description: Department not found

components:
  schemas:
    Department:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        location:
          type: string
    DepartmentInput:
      type: object
      properties:
        name:
          type: string
          example: Recursos Humanos
        location:
          type: string
          example: Quito
    Employee:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        position:
          type: string
        departmentId:
          type: integer
        email:
          type: string
        salary:
          type: number
    EmployeeInput:
      type: object
      properties:
        name:
          type: string
          example: Juan Pérez
        position:
          type: string
          example: Analista
        departmentId:
          type: integer
          example: 1
        email:
          type: string
          example: juan.perez@empresa.com
        salary:
          type: number
          example: 1200.50
